### ISSUE TITLE
Compass is deprecated; migrate to sass

### ISSUE THREAD

**Issue by fitzgerald** [pgharts/trusty-cms#317]
https://github.com/sass/sassc-rails

**Comment by tysongach** [comment]
I think we should update/break-up this ticket. There's two separate tasks here:

1. [Compass](https://github.com/Compass/compass) is built on top of, and is a framework for, Sass. We should remove Compass (done in https://github.com/pgharts/trusty-cms/pull/318) because it is no longer actively maintained.
2. We should keep Sass, but move off of Ruby Sass. [Sass’s Ruby implementation](https://github.com/sass/ruby-sass) is in a sunset period and will no longer be supported as of March 26, 2019. They encourage folks to move to sassc, e.g. the [sassc-rails gem](https://github.com/sass/sassc-rails)

**Comment by fitzgerald** [comment]
Thank you! I'm going to close this ticket as #318 and open a new ticket for Ruby Sass.
